apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
spec:
  selector:
    matchLabels:
      run: proxy-server
  replicas: 1
  template:
    metadata:
      labels:
        run: proxy-server
    spec:
      hostNetwork: true
      containers:
      - name: proxy-server
        image: stegala/plebiscito-proxy:0.1
        env:
        - name: LOCAL_PORT
          value: "9191"
        - name: LOCAL_ADDRESS
          value: "192.168.11.90"
        - name: REMOTE_PORT
          value: "31218"
        - name: REMOTE_ADDRESS
          value: "192.168.11.90"
        ports:
        - containerPort: 9191
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: proxy-server
#   labels:
#     run: proxy-server
# spec:
#   type: NodePort
#   ports:
#   - port: 9191
#     protocol: TCP
#   selector:
#     run: proxy-server